### ISSUE TITLE
style sidebar

### ISSUE THREAD

**Issue by VicoSneepPP** [PlusPort/PlusPort-Direct-theme#42]

**Comment by RuggeroUdondekPP** [comment]
Sidebar has been styled, only thing left is the 'Enkele van onze klanten' field. I was thinking of using a jQuery slider to create it, but I checked the one on PlusPort.com and it also uses PHP. It works a bit different, I think Peter created it? Do you know how to recreate/ easily implement it on this website? If not, we can still use a more basic jQuery slider (without the use of PHP)

**Comment by VicoSneepPP** [comment]
Widgets has not been used. Dynamic text blocks which offers flexibility with images, sliders and html
