### ISSUE TITLE
Style submenu Template training

### ISSUE THREAD

**Issue by VicoSneepPP** [PlusPort/PlusPort-Direct-theme#44]
De submenu in the template Training is now a list. This should be a horizontal menu beneath the slider

**Comment by RuggeroUdondekPP** [comment]
As good as done, there is a problem though. Only the parent shows their siblings, The siblings don't show their parent and brothers and sisters :'(. I think the underneath PHP script needs to be rewritten (a bit). I've been trying to figure it out, but with my PHP knowledge, so far no solution.

 <?php

             // parent (or self) is first tab
             echo '<li><a href="' . get_page_link($parent->ID) . '">' . $parent->post_title . '</a></li>';
             // tabs are siblings

             if(is_array($siblings) && !empty($siblings)){

                 foreach($siblings as $sibling){
                    echo '<li><a href="' . get_page_link($sibling->ID) . '">' . $sibling->post_title . '</a></li>';
                 }
             }
             ?>
